In [58]:
!pip install keras
!pip install tensorflow


In [13]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
sns.set()

In [14]:
dataset = pd.read_csv('Churn_Modelling.csv', index_col = 'RowNumber')
dataset.head()

CustomerId   Surname  CreditScore Geography  Gender  Age  Tenure  \
RowNumber                                                                     
1            15634602  Hargrave          619    France  Female   42       2   
2            15647311      Hill          608     Spain  Female   41       1   
3            15619304      Onio          502    France  Female   42       8   
4            15701354      Boni          699    France  Female   39       1   
5            15737888  Mitchell          850     Spain  Female   43       2   

             Balance  NumOfProducts  HasCrCard  IsActiveMember  \
RowNumber                                                        
1               0.00              1          1               1   
2           83807.86              1          0               1   
3          159660.80              3          1               0   
4               0.00              2          0               0   
5          125510.82              1          1               1   

           EstimatedSalary  Exited  
RowNumber                           
1                101348.88       1  
2                112542.58       0  
3                113931.57       1  
4                 93826.63       0  
5                 79084.10       0

In [15]:
X_columns = dataset.columns.tolist()[2:12]
Y_columns = dataset.columns.tolist()[-1:]
print(X_columns)
print(Y_columns)

['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']
['Exited']


In [16]:
X = dataset[X_columns].values 
Y = dataset[Y_columns].values

In [17]:
from sklearn.preprocessing import LabelEncoder
X_column_transformer = LabelEncoder()
X[:, 1] = X_column_transformer.fit_transform(X[:, 1])

In [18]:
X[:, 2] = X_column_transformer.fit_transform(X[:, 2])

In [19]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
pipeline = Pipeline(
    [
        ('Categorizer', ColumnTransformer(
            [
                ("Gender Label Encoder", OneHotEncoder(categories = 'auto', drop = 'first'), [2]),
                ("Geography Label Encoder", OneHotEncoder(categories = 'auto', drop = 'first'), [1])
            ], 
            remainder = 'passthrough', n_jobs = 1)),
        ('Normalizer', StandardScaler())
    ]
)

In [20]:
X = pipeline.fit_transform(X)

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [22]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Input

# Initialize the classifier
classifier = Sequential()

# Add input layer and hidden layer
classifier.add(Input(shape=(X_train.shape[1],)))  # Input layer defines the input shape
classifier.add(Dense(units=6, activation='relu'))
classifier.add(Dropout(rate=0.1))

In [23]:
#Add second layer
classifier.add(Dense(6, activation = 'relu'))
classifier.add(Dropout(rate = 0.1))

In [24]:
#Add output layer
classifier.add(Dense(1, activation = 'sigmoid'))

In [25]:
#Let us take a look at our network
classifier.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 6)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 6)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 6)              │            42 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 6)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             7 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 121 (484.00 B)

 Trainable params: 121 (484.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
#Optimize the weights
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [27]:
#Fitting the Neural Network
history = classifier.fit(X_train, y_train, batch_size = 32, epochs = 200, validation_split = 0.1, verbose = 2)

Epoch 1/200
225/225 - 2s - 10ms/step - accuracy: 0.7753 - loss: 0.5310 - val_accuracy: 0.7950 - val_loss: 0.4558
Epoch 2/200
225/225 - 0s - 2ms/step - accuracy: 0.7953 - loss: 0.4675 - val_accuracy: 0.7950 - val_loss: 0.4366
Epoch 3/200
225/225 - 1s - 2ms/step - accuracy: 0.7965 - loss: 0.4556 - val_accuracy: 0.7975 - val_loss: 0.4259
Epoch 4/200
225/225 - 1s - 3ms/step - accuracy: 0.7968 - loss: 0.4499 - val_accuracy: 0.7987 - val_loss: 0.4193
Epoch 5/200
225/225 - 0s - 2ms/step - accuracy: 0.8011 - loss: 0.4467 - val_accuracy: 0.8000 - val_loss: 0.4158
Epoch 6/200
225/225 - 0s - 2ms/step - accuracy: 0.8051 - loss: 0.4390 - val_accuracy: 0.8062 - val_loss: 0.4136
Epoch 7/200
225/225 - 0s - 2ms/step - accuracy: 0.8086 - loss: 0.4413 - val_accuracy: 0.8138 - val_loss: 0.4114
Epoch 8/200
225/225 - 1s - 2ms/step - accuracy: 0.8097 - loss: 0.4382 - val_accuracy: 0.8250 - val_loss: 0.4099
Epoch 9/200
225/225 - 1s - 2ms/step - accuracy: 0.8119 - loss: 0.4362 - val_accuracy: 0.8250 - val_loss

In [32]:
y_pred = classifier.predict(X_test)
print(y_pred[:5])

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0.28140223]
 [0.2462825 ]
 [0.19887497]
 [0.0717828 ]
 [0.11744692]]


In [33]:
#Let us use confusion matrix with cutoff value as 0.5
y_pred = (y_pred > 0.5).astype(int)
print(y_pred[:5])

[[0]
 [0]
 [0]
 [0]
 [0]]


In [30]:
#Making the Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1526   69]
 [ 194  211]]


In [31]:
#Accuracy of our NN
print(((cm[0][0] + cm[1][1])* 100) / len(y_test), '% of data was classified correctly')

86.85 % of data was classified correctly
